### ISSUE TITLE
Explore Adding Metrics Endpoint and Service Monitor

### ISSUE THREAD

**Issue by rwh85** [defenseunicorns/uds-package-postgres-operator#51]
### Is your feature request related to a problem? Please describe.
Package doesn't expose a metrics endpoint. This feature will aim to add a metrics endpoint using postgres-exporter and then configure a servicemonitor to integrate with the UDS Core Prometheus Operator

### Describe the solution you'd like
Provide an option in the helm chart to configure monitoring. 

Given it's enabled, the postgres operator will be configured via the OperatorConfiguration CR or in the helm chart. Then using the Package CR a service monitor will be created to connect Prometheus Operator and postgres exporter. 

### Describe alternatives you've considered
I've look and the zalando images and charts don't enable this functionality. Also there are sever issues the most useful of which is https://github.com/zalando/postgres-operator/issues/264 which has been open for year.

**Comment by Racer159** [comment]
Completed in #53
